// Include MicroPython API.
#include "py/runtime.h"

// Declare the functions we'll make available in Python
extern mp_obj_t esp32spi_init();
extern mp_obj_t esp32spi_reset();
extern mp_obj_t esp32spi_status();
extern mp_obj_t esp32spi_firmware_version();
extern mp_obj_t esp32spi_MAC_address();
extern mp_obj_t esp32spi_MAC_address_actual();
extern mp_obj_t esp32spi_start_scan_networks();
extern mp_obj_t esp32spi_get_scan_networks();
extern mp_obj_t esp32spi_scan_networks();
extern mp_obj_t esp32spi_wifi_set_network(mp_obj_t ssid);
extern mp_obj_t esp32spi_wifi_set_passphrase(mp_obj_t ssid, mp_obj_t passphrase);
extern mp_obj_t esp32spi_wifi_set_entidentity(mp_obj_t ident);
extern mp_obj_t esp32spi_wifi_set_entusername(mp_obj_t username);
extern mp_obj_t esp32spi_wifi_set_entpassword(mp_obj_t password);
extern mp_obj_t esp32spi_wifi_set_entenable();
extern mp_obj_t esp32spi_ssid();
extern mp_obj_t esp32spi_bssid();
extern mp_obj_t esp32spi_rssi();
extern mp_obj_t esp32spi_network_data();
extern mp_obj_t esp32spi_ip_address();
extern mp_obj_t esp32spi_is_connected();
extern mp_obj_t esp32spi_ap_listening();
extern mp_obj_t esp32spi_disconnect();
extern mp_obj_t esp32spi_connect(mp_obj_t secrets);
extern mp_obj_t esp32spi_connect_AP(mp_obj_t ssid, mp_obj_t password, mp_obj_t timeout_s/* = 10*/);
extern mp_obj_t esp32spi_create_AP(mp_uint_t n_args, const mp_obj_t *args);//(mp_obj_t ssid, mp_obj_t password, mp_obj_t channel/* = 1*/, mp_obj_t timeout/* = 10*/);
extern mp_obj_t esp32spi_pretty_ip(mp_obj_t ip);
extern mp_obj_t esp32spi_unpretty_ip(mp_obj_t ip);
extern mp_obj_t esp32spi_get_host_by_name(mp_obj_t hostname);
extern mp_obj_t esp32spi_ping(mp_obj_t dest, mp_obj_t ttl/* = 250*/);
extern mp_obj_t esp32spi_get_socket();
extern mp_obj_t esp32spi_socket_open(mp_uint_t n_args, const mp_obj_t *args);//(mp_obj_t socket_num, mp_obj_t dest, mp_obj_t port, mp_obj_t conn_mode/* = TCP_MODE*/);
extern mp_obj_t esp32spi_socket_status(mp_obj_t socket_num);
extern mp_obj_t esp32spi_socket_connected(mp_obj_t socket_num);
extern mp_obj_t esp32spi_socket_write(mp_obj_t socket_num, mp_obj_t buffer, mp_obj_t conn_mode/* = TCP_MODE*/);
extern mp_obj_t esp32spi_socket_available(mp_obj_t socket_num);
extern mp_obj_t esp32spi_socket_read(mp_obj_t socket_num, mp_obj_t size);
extern mp_obj_t esp32spi_socket_connect(mp_uint_t n_args, const mp_obj_t *args);//(mp_uint_t n_args, const mp_obj_t *args);//(mp_obj_t socket_num, mp_obj_t dest, mp_obj_t port, mp_obj_t conn_mode/* = TCP_MODE*/);
extern mp_obj_t esp32spi_socket_close(mp_obj_t socket_num);
extern mp_obj_t esp32spi_start_server(mp_uint_t n_args, const mp_obj_t *args);//(mp_obj_t port, mp_obj_t socket_num, mp_obj_t conn_mode/* = TCP_MODE*/, mp_obj_t ip/* = None*/);
extern mp_obj_t esp32spi_server_state(mp_obj_t socket_num);
extern mp_obj_t esp32spi_esp_debug(mp_obj_t enabled);
extern mp_obj_t esp32spi_set_pin_mode(mp_obj_t pin, mp_obj_t mode);
extern mp_obj_t esp32spi_set_digital_write(mp_obj_t pin, mp_obj_t value);
extern mp_obj_t esp32spi_set_analog_write(mp_obj_t pin, mp_obj_t analog_value);
extern mp_obj_t esp32spi_set_digital_read(mp_obj_t pin);
extern mp_obj_t esp32spi_set_analog_read(mp_obj_t pin, mp_obj_t atten/* = ADC_ATTEN_DB_11*/);
extern mp_obj_t esp32spi_get_time();
extern mp_obj_t esp32spi_set_certificate(mp_obj_t client_certificate);
extern mp_obj_t esp32spi_set_private_key(mp_obj_t private_key);