include(${CMAKE_CURRENT_LIST_DIR}/breakout_dotmatrix/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_ltr559/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_colourlcd160x80/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_as7262/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_roundlcd/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_rgbmatrix5x5/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_matrix11x7/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_trackball/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_sgp30/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/breakout_colourlcd240x240/micropython.cmake)

include(${CMAKE_CURRENT_LIST_DIR}/pico_scroll/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_rgb_keypad/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_unicorn/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_display/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_explorer/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_wireless/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ulab/code/micropython.cmake)
