include(${CMAKE_CURRENT_LIST_DIR}/pico_scroll/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_rgb_keypad/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_unicorn/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_display/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_explorer/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/esp32spi/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ulab/code/micropython.cmake)
