include(${CMAKE_CURRENT_LIST_DIR}/pico_scroll/usermod.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_rgb_keypad/usermod.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_unicorn/usermod.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_display/usermod.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pico_explorer/usermod.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ulab/code/usermod.cmake)
